"""
KG-Verify-HITL global configuration.
All LLM config, thresholds, paths, and rule sets live here.
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# ─── Paths ────────────────────────────────────────────────────────────────────
ROOT_DIR = Path(__file__).parent.parent
KG_FILE = Path("/Users/darrenlong/Desktop/长江/knowledge graph/CPubMed-KGv2_0.txt")
OUTPUT_DIR = ROOT_DIR / "outputs"
OUTPUT_DIR.mkdir(exist_ok=True)
(OUTPUT_DIR / "approved_patches").mkdir(exist_ok=True)

# ─── LLM config (DeepSeek V4 flash, OpenAI-compatible) ───────────────────────
LLM_CFG = {
    "model": "deepseek-chat",          # deepseek-v4-flash maps to deepseek-chat on v1
    "model_server": "https://api.deepseek.com/v1",
    "api_key": os.environ.get("DEEPSEEK_API_KEY", ""),
    "generate_cfg": {
        "top_p": 0.8,
        "temperature": 0.0,
        "max_input_tokens": 8000,
    },
}

# ─── Gold-label LLM config (Agent G) ─────────────────────────────────────────
# Use a DIFFERENT model family for Agent G (SimulatedHumanReviewerAgent) to
# avoid circular evaluation: the system agents use DeepSeek; Agent G should use
# a different model so gold labels are generated by an independent reasoning engine.
#
# Priority order:
#   1. OPENAI_API_KEY set → use GPT-4o (best independence from DeepSeek)
#   2. QWEN_API_KEY set → use Qwen-Max (different architecture)
#   3. Fallback → DeepSeek-Reasoner (different reasoning mode from deepseek-chat)
_openai_key = os.environ.get("OPENAI_API_KEY", "")
_qwen_key = os.environ.get("QWEN_API_KEY", os.environ.get("DASHSCOPE_API_KEY", ""))

if _openai_key:
    GOLD_LLM_CFG = {
        "model": "gpt-4o",
        "model_server": "https://api.openai.com/v1",
        "api_key": _openai_key,
        "generate_cfg": {
            "temperature": 0.0,
            "max_input_tokens": 8000,
        },
    }
elif _qwen_key:
    GOLD_LLM_CFG = {
        "model": "qwen-max",
        "model_server": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "api_key": _qwen_key,
        "generate_cfg": {
            "temperature": 0.0,
            "max_input_tokens": 8000,
        },
    }
else:
    # Fallback: DeepSeek-Reasoner uses chain-of-thought, architecturally distinct
    # from deepseek-chat (system agents A-F). Reasoner temperature is fixed at 1.0.
    GOLD_LLM_CFG = {
        "model": "deepseek-reasoner",
        "model_server": "https://api.deepseek.com/v1",
        "api_key": os.environ.get("DEEPSEEK_API_KEY", ""),
        "generate_cfg": {
            "temperature": 1.0,
            "max_input_tokens": 6000,
        },
    }

GOLD_MODEL_NAME: str = GOLD_LLM_CFG["model"]  # for logging / paper reporting

# ─── Pipeline mode ────────────────────────────────────────────────────────────
# "production"  → exports review_items.tsv; waits for human TSV import
# "simulation"  → Agent G (SimulatedHumanReviewerAgent) plays the human role
PIPELINE_MODE: str = os.environ.get("PIPELINE_MODE", "simulation")

# ─── Detection thresholds ─────────────────────────────────────────────────────
SCHEMA_THRESHOLD_EXTREME: float = 0.005      # < 0.5% → MACHINE_SUSPECTED
SCHEMA_THRESHOLD_BORDERLINE: float = 0.05   # 0.5–5% → softer flag (Agent B)
AUTO_CLEAN_SCORE: float = 0.15              # composite < 0.15 → AUTO_CLEAN
CARDINALITY_MULTIPLIER: float = 10.0        # actual > 10x median → flag
# Round 2 fix: hub threshold recalibrated for full 4.58M triple KG.
# Pilot (50K triples) had max_degree ~100; full KG max_degree=33,617.
# threshold=50 routed 45.5% of MACHINE_SUSPECTED to uncertain_hub→Agent E,
# which dramatically hurt performance (A0 AUPRC=0.4479 vs A1=0.7483).
# At threshold=5000, only extreme hubs (top ~1% by degree) invoke Agent E.
HUB_DEGREE_THRESHOLD: int = 5000           # degree ≥ 5000 → invoke Agent E
SYMMETRIC_COVERAGE_THRESHOLD: float = 0.60  # > 60% symmetric pairs → r is symmetric

# ─── Scoring weights ──────────────────────────────────────────────────────────
# V2 fix (Loop 2, Round 1): collapse to schema-only scoring.
# 4-round ablation (seeds 42/456/789/101) consistently showed:
#   A4 (card=0): 0.5840→0.7199 AUPRC avg (+0.114 vs A0)
#   A5 (struct=0): same improvement as A4
# Both A4 and A5 effectively make composite_score ≈ f(schema_score) only.
# V2 makes this explicit: set schema=1.0, others=0.0.
# Schema violation score (pattern frequency rarity) is the cleanest pre-filter
# for true errors; cardinality and structural signals add noise without precision.
SCORING_WEIGHTS = {
    "schema_violation": 1.0,
    "cardinality_anomaly": 0.0,
    "structural_score": 0.0,
}

# V2: route-conditioned verification hints (Loop 2 technical innovation)
# 4-round ablation showed A3 (no evidence context) AUPRC=0.6538 > A0=0.6061 (+0.048):
# raw neighbor context adds noise to Agent A's reasoning.
# V2 replaces raw neighbor_summary with structured route hints — a machine-generated
# brief explaining WHY the triple was flagged by statistical pre-screening.
# V2.1: Route hints empirically harmful (-0.309 AUPRC, B3=0.9201 >> B0=0.6108 in seed=202).
# Anchoring bias: suspicion brief causes Agent A to confirm false positives.
# V2.1 disables hints; Agent A receives minimal pkg (triple+types+schema_stats) only.
USE_ROUTE_HINTS: bool = False

# V3.0: Two-Round Agent A Ensemble (Loop 3 architectural innovation)
# When True, replaces single SemanticPlausibilityAgent with SemanticPlausibilityEnsembleAgent.
# Ensemble runs Agent A twice: once schema-aware, once semantic-only.
# Cross-context agreement → HIGH (1.0); single flag → MEDIUM (0.6);
# conflicted (schema says IMPLAUSIBLE, semantic says PLAUSIBLE) → UNCERTAIN (0.0).
# This demotes schema-rare-but-medically-valid FALSE_ALARMs that currently
# crowd the top-K list, improving AUPRC at moderate scale.
# Set via env var ENSEMBLE_AGENT_A=1 or directly in ablation configs.
USE_ENSEMBLE_AGENT_A: bool = os.environ.get("ENSEMBLE_AGENT_A", "0") == "1"

# ─── Relation semantics (verify from data) ────────────────────────────────────
POTENTIALLY_REFLEXIVE_RELATIONS: set[str] = {
    "同义词", "相同概念", "同类", "相关",
}

CONTRADICTORY_RELATION_PAIRS: set[tuple[str, str]] = {
    ("治疗", "禁忌"),
    ("适应症", "禁忌"),
    ("促进", "抑制"),
    ("增加", "减少"),
}

HIGH_RISK_RELATIONS: set[str] = {
    "禁忌", "不良反应", "副作用", "毒性", "过量",
    "药物治疗", "治疗", "手术治疗", "化疗",
}

# ─── Classification states ────────────────────────────────────────────────────
AUTO_CLEAN = "AUTO_CLEAN"
AUTO_ACTION_SAFE = "AUTO_ACTION_SAFE"
MACHINE_SUSPECTED = "MACHINE_SUSPECTED"
AGENT_SUSPECTED = "AGENT_SUSPECTED"
AGENT_REPAIR_CANDIDATE = "AGENT_REPAIR_CANDIDATE"
HUMAN_APPROVED_REPAIR = "HUMAN_APPROVED_REPAIR"
HUMAN_APPROVED_DELETE = "HUMAN_APPROVED_DELETE"
HUMAN_REJECTED = "HUMAN_REJECTED"
HUMAN_DEFERRED = "HUMAN_DEFERRED"

# ─── Patch write decisions ────────────────────────────────────────────────────
WRITE_DECISIONS: set[str] = {
    "APPROVE_DELETE",
    "APPROVE_RELATION_REPLACE",
    "APPROVE_ENTITY_REPLACE",
    "APPROVE_ADD_REVERSE",
    "APPROVE_ENTITY_MERGE",
}

# ─── Review priority weights ──────────────────────────────────────────────────
# V3.0 fix (Loop 3, Round 1): Empirical analysis on 504-item fixed eval set
# (n_true=81) showed that the previous formula DILUTED the agent_confidence
# signal by mixing in composite_score (schema-only AUPRC=0.43 alone, adding
# noise when combined with agent_conf AUPRC=0.96 alone).
#
# Data-driven finding:
#   agent_confidence alone:       AUPRC = 0.9576
#   current formula (C1):         AUPRC = 0.7216   (-0.236 vs agent_conf alone)
#   composite_score alone (C2):   AUPRC = 0.4307
#
# Root cause: agent_confidence * 0.40 vs composite_score * 0.30 allows
# schema-extreme but PLAUSIBLE items to rank above Agent-A-flagged errors.
# At 200K scale, schema stats are noisier → many FALSE_ALARMs have high
# composite_score, directly competing with TRUE_ERRORs in priority ranking.
#
# V3.0 fix: maximize agent_confidence weight (0.40→0.85), minimize
# composite_score (0.30→0.05), remove impact/degree/repair_quality (all
# empirically neutral or harmful per Loop 2 ablations).
# Medical risk kept at 0.10: HIGH_RISK_RELATIONS are genuine safety signals
# independent of Agent A's semantic plausibility check.
PRIORITY_WEIGHTS = {
    "composite_score": 0.05,
    "agent_confidence": 0.85,
    "impact_score": 0.00,
    "degree_score": 0.00,
    "medical_risk_score": 0.10,
    "repair_quality": 0.00,
}

# ─── Audit sample rates ───────────────────────────────────────────────────────
AUDIT_SAMPLE_RATES = {
    "self_loop": 0.05,
    "exact_duplicate": 0.01,
    "parse_error": 0.05,
    "add_reverse": 0.10,
}

# ─── Experiment / ablation configuration ─────────────────────────────────────
# FLAT_LLM_MODE: bypass topology-aware routing; send all MACHINE_SUSPECTED
# through Agent A only. Used for the flat-LLM baseline experiment.
FLAT_LLM_MODE: bool = os.environ.get("FLAT_LLM_MODE", "0") == "1"

# Gold set stratified sampling targets (total = sum of values = 500)
GOLD_STRATA: dict[str, int] = {
    "auto_clean": 100,
    "schema_extreme": 100,
    "leaf_suspected": 150,
    "hub_suspected": 100,
    "auto_action_safe": 50,
}
GOLD_SET_N: int = sum(GOLD_STRATA.values())  # 500
PILOT_N: int = 50  # triples per condition in the pilot experiment

# Pilot signal threshold (from IDEA_REPORT.md §5)
PILOT_PRECISION_THRESHOLD: float = 0.60    # Routed P@25 must be >= this
PILOT_MARGIN_THRESHOLD: float = 0.10       # delta must be >= this

GOLD_OUTPUT_DIR: Path = ROOT_DIR / "gold_samples"
GOLD_OUTPUT_DIR.mkdir(exist_ok=True)
RESULTS_DIR: Path = ROOT_DIR / "results"
RESULTS_DIR.mkdir(exist_ok=True)
